# Generated by Django 3.1.5 on 2021-01-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lobby_details',
            fields=[
                ('lobby_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='lobby_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('revenue', models.FloatField(null=True)),
                ('max_members_allowed', models.IntegerField(default=2)),
                ('lobby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.lobby_details')),
                ('winner_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.user_details')),
            ],
        ),
    ]
