# Generated by Django 3.1.5 on 2021-01-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lobby_user_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='lobby_details',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lobby_details',
            name='max_members_allowed',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lobby_details',
            name='revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lobby_details',
            name='winner_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.user_details'),
        ),
        migrations.DeleteModel(
            name='lobby_status',
        ),
        migrations.AddField(
            model_name='lobby_user_map',
            name='lobby_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.lobby_details'),
        ),
        migrations.AddField(
            model_name='lobby_user_map',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.user_details'),
        ),
    ]
